import { ThunkDispatch } from '@reduxjs/toolkit'
import { useTheme } from '@shopify/restyle'
import { useEffect, useState } from 'react'
import { AccessibilityInfo } from 'react-native'
import { TypedUseSelectorHook, useDispatch, useSelector } from 'react-redux'
import { SelectEffect } from 'redux-saga/effects'
import type { RootState } from 'src/app/rootReducer'
import type { AppDispatch } from 'src/app/store'
import type { Theme } from 'src/styles/theme'
imp